#nqueens
# PROBID: Identifier of each problem (used in test_main to de

# PROBID = 0
PROBPATH = ../nqueens/
PROBOBJ = nqueens.o

PROBINIT = problem_init/nqueens_init.c

# MACROS
GETOBJECTIVEVALUE=1
GETOBJECTIVEVECTOR=1
GETOBJECTIVEIINCREMENT=1

GETNEIGHBOURHOODSIZE=1
GETEXCENTRICITY=1
GETLENGTH=1
 
EQUALSOLUTIONS=1

RANDOMSOLUTION=1
RANDOMSOLUTIONINSEGMENT=1
 
RANDOMMOVE=1
RANDOMMOVETOWARDS=1
RANDOMMOVEWOR=1
RANDOMMOVETOWARDSWOR=1

RANDOMMOVEAWAY=1
RANDOMMOVEAWAYWOR=1

RANDOMNEIGHBOUR=1
RANDOMNEIGHBOURTOWARDS=1

RESETRANDOMMOVEWOR=1

COPYSOLUTION=1
COPYMOVE=0

APPLYMOVE=1
APPLYMOVETOSEGMENT=1
